version: '2'
services:
  ldapserver:
    image: 'francesco19/ldap_server_exam_ns:latest'
    stdin_open: true
    tty: true
    ports:
      - '1389:1389'
      - '8888:8888'
    networks:
      network_1:
        ipv4_address: 193.20.1.3
  netcat:
    image: 'busybox:latest'
    stdin_open: true
    tty: true
    networks:
      network_1:
        ipv4_address: 193.20.1.4
  client:
    image: 'arunvelsriram/utils:latest'
    stdin_open: true
    tty: true
    networks:
      network_1:
        ipv4_address: 193.20.1.5
  vulnerable-app:
    image: 'ghcr.io/christophetd/log4shell-vulnerable-app:latest'
    stdin_open: true
    tty: true
    ports:
      - '8080:8080'
    networks:
      network_1:
        ipv4_address: 193.20.1.2
networks:
  network_1:
    ipam:
      config:
        - subnet: 193.20.1.1/24
